In [7]:
import os, re, time
import pandas as pd
from tqdm.auto import tqdm

CORPUS = "/Users/gmello/Documents/python_repos/mestrado/resultados_experimentos"
UA     = "/Users/gmello/Documents/python_repos/mestrado/ua-dd-saea"

ALGORITMOS = ['b1',   'b3',   'b4',   'b5m',  'b5r',
              'c122', 'c141', 'c149', 'c154', 'c217', 
              'c238', 'c262', 'e7',   'e74',  'e81'  'e103'
             ]

PROBLEMAS = ["ZDT1", "ZDT3", "ZDT4", "ZDT6", "DTLZ1", "DTLZ2", "DTLZ3", "DTLZ4", "DTLZ7",
             "WFG1", "WFG2", "WFG4", "WFG5", "WFG9", "MMF1", "MMF4", "MMF11_L", "MMF16_20",
             "BBOB_F1", "BBOB_F5", "BBOB_F17", "BBOB_F22", "BBOB_F37", "BBOB_F49", "BBOB_F55",
             "RE21", "ESTOQUE40", "DDMOP7"]

SEEDS = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,42]

/Users/gmello/Documents/python_venvs/ds_controle_sintetico/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [13]:
for algoritmo in tqdm([ALGORITMOS[0]]):
    for problema in tqdm([PROBLEMAS[0]]):
        for seed in tqdm([SEEDS[0]]):
            df_real      = pd.read_parquet(f'{CORPUS}/{algoritmo}/{problema}/{seed}/exp_main_{algoritmo}_{problema}_{seed}__real.parquet')
            df_surrogate = pd.read_parquet(f'{CORPUS}/{algoritmo}/{problema}/{seed}/exp_main_{algoritmo}_{problema}_{seed}__surrogate.parquet')
            df_populacao = pd.read_parquet(f'{CORPUS}/{algoritmo}/{problema}/{seed}/exp_main_{algoritmo}_{problema}_{seed}__pop.parquet')

  0%|          | 0/1 [00:00<?, ?it/s]



100%|██████████| 1/1 [00:00<00:00,  2.94it/s]
100%|██████████| 1/1 [00:00<00:00,  2.92it/s]
100%|██████████| 1/1 [00:00<00:00,  2.89it/s]

In [14]:
df_real

,algoritmo,problema,semente,solution_id,x0,x1,x2,x3,x4,x5,...,x24,x25,x26,x27,x28,x29,f0,f1,fe_index,fase
0,b1,ZDT1,0,0,0.060206,0.721807,2.307686e-01,2.500544e-01,0.773303,0.867650,...,0.476307,0.041338,0.810764,0.955238,0.250875,0.456458,0.060206,4.756007,0,init
1,b1,ZDT1,0,1,0.591885,0.621772,9.792924e-01,1.067928e-01,0.233654,0.666879,...,0.540039,0.981335,0.749624,0.475892,0.255840,0.475935,0.591885,3.827752,1,init
2,b1,ZDT1,0,2,0.575974,0.237442,4.395959e-01,3.508145e-01,0.944877,0.896360,...,0.722136,0.224875,0.149413,0.044988,0.826302,0.370285,0.575974,4.090075,2,init
3,b1,ZDT1,0,3,0.123474,0.326515,4.098602e-01,8.515895e-01,0.475090,0.276790,...,0.642441,0.963884,0.957569,0.852061,0.530167,0.605943,0.123474,4.864097,3,init
4,b1,ZDT1,0,4,0.861395,0.780289,8.944584e-01,5.930105e-01,0.272550,0.732784,...,0.396485,0.990658,0.683578,0.645682,0.296969,0.680824,0.861395,3.634313,4,init
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
924,b1,ZDT1,0,924,0.000000,0.000001,4.244117e-03,7.457090e-01,0.013823,0.000000,...,0.000545,0.001385,0.000542,0.040294,0.000525,0.751493,0.000000,1.607028,924,opt
925,b1,ZDT1,0,925,0.999891,0.001431,1.618202e-04,3.467236e-05,0.001457,0.000405,...,0.000090,0.003001,0.002194,0.001585,0.000045,0.000000,0.999891,0.171435,925,opt
926,b1,ZDT1,0,926,0.999995,0.000226,0.000000e+00,3.364679e-07,0.000769,0.000000,...,0.000173,0.000304,0.001346,0.000024,0.000172,0.000009,0.999995,0.162660,926,opt
927,b1,ZDT1,0,927,1.000000,0.000226,7.223768e-07,1.773489e-04,0.000609,0.000000,...,0.000000,0.000000,0.001350,0.000514,0.000178,0.000015,1.000000,0.168228,927,opt
928,b1,ZDT1,0,928,0.002470,0.055432,7.121590e-04,2.575465e-03,0.001966,0.007601,...,0.000339,0.001441,0.000322,0.000169,0.015813,0.000000,0.002470,1.039115,928,opt

In [15]:
df_surrogate

,algoritmo,problema,semente,regime,geracao,x0,x1,x2,x3,x4,...,sigma_1,pred_tipo,pred_classe,pred_score,pred_confianca,modelo_flag,espaco_modelo,transf_tipo,transf_params,fe_treino_max
0,b1,ZDT1,0,sonda,1,0.207533,0.612712,0.834503,0.010893,0.011058,...,NaN,valor,NaN,NaN,NaN,GP-DACE,transformado,escalar-tcheby,"{""lambda"":[0.81818181818181823,0.1818181818181...",328
1,b1,ZDT1,0,sonda,1,0.737878,0.493902,0.493329,0.917866,0.611316,...,NaN,valor,NaN,NaN,NaN,GP-DACE,transformado,escalar-tcheby,"{""lambda"":[0.81818181818181823,0.1818181818181...",328
2,b1,ZDT1,0,sonda,1,0.811623,0.986764,0.604735,0.370947,0.838055,...,NaN,valor,NaN,NaN,NaN,GP-DACE,transformado,escalar-tcheby,"{""lambda"":[0.81818181818181823,0.1818181818181...",328
3,b1,ZDT1,0,sonda,1,0.273484,0.118015,0.191968,0.713967,0.281758,...,NaN,valor,NaN,NaN,NaN,GP-DACE,transformado,escalar-tcheby,"{""lambda"":[0.81818181818181823,0.1818181818181...",328
4,b1,ZDT1,0,sonda,1,0.462642,0.803415,0.304345,0.563174,0.423603,...,NaN,valor,NaN,NaN,NaN,GP-DACE,transformado,escalar-tcheby,"{""lambda"":[0.81818181818181823,0.1818181818181...",328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382379,b1,ZDT1,0,sonda,609,0.389513,0.207813,0.486510,0.992438,0.703935,...,NaN,valor,NaN,NaN,NaN,GP-DACE,transformado,escalar-tcheby,"{""lambda"":[0.96969696969696972,0.0303030303030...",924
1382380,b1,ZDT1,0,sonda,609,0.327571,0.901030,0.001079,0.847578,0.564043,...,NaN,valor,NaN,NaN,NaN,GP-DACE,transformado,escalar-tcheby,"{""lambda"":[0.96969696969696972,0.0303030303030...",924
1382381,b1,ZDT1,0,sonda,609,0.852033,0.015672,0.670618,0.190586,0.057839,...,NaN,valor,NaN,NaN,NaN,GP-DACE,transformado,escalar-tcheby,"{""lambda"":[0.96969696969696972,0.0303030303030...",924
1382382,b1,ZDT1,0,sonda,609,0.661090,0.527099,0.309215,0.518637,0.266532,...,NaN,valor,NaN,NaN,NaN,GP-DACE,transformado,escalar-tcheby,"{""lambda"":[0.96969696969696972,0.0303030303030...",924
1382383,b1,ZDT1,0,sonda,609,0.128788,0.391681,0.893609,0.425621,0.853773,...,NaN,valor,NaN,NaN,NaN,GP-DACE,transformado,escalar-tcheby,"{""lambda"":[0.96969696969696972,0.0303030303030...",924

In [18]:
import plotly.express as px
px.bar(df_populacao.groupby('geracao').size().reset_index(name = 'tam_pop'), x = 'geracao', y = 'tam_pop')

0it [56:40, ?it/s]